x-common: &common
  tty: true
  working_dir: /workspace
  networks:
    - app-network
  volumes:
    - .:/workspace
    - ${HOME}/.config/gh:/home/${USERNAME}/.config/gh:ro
    - ${HOME}/.gitconfig:/home/${USERNAME}/.gitconfig:ro
    - ${HOME}/.ssh:/home/${USERNAME}/.ssh:ro
    - ${HOME}/.zsh_history:/home/${USERNAME}/.zsh_history
    - ./apt-packages.txt:/home/${USERNAME}/apt-packages.txt
    - ${HOME}/.claude:/home/${USERNAME}/.claude
    - ${HOME}/.claude.json:/home/${USERNAME}/.claude.json

networks:
  app-network:
    driver: bridge

services:
  # Agent コンテナ（FastAPI）
  claude:
    build:
      context: .
      dockerfile: Dockerfile.claude
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}-claude
    image: local/claude:latest
    environment:
      CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}-claude
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      LC_ALL: ja_JP.UTF-8
    expose:
      - "8001"
    command: ["sh", "-c", "cd /workspace && python3 agent/main.py"]
    profiles: ["claude", "typescript", "api"]
    <<: *common

  # API Gateway（FastAPI）
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    image: local/api-gateway:latest
    environment:
      CLAUDE_URL: http://claude:8001
    ports:
      - "8000:8000"
    depends_on:
      - claude
    profiles: ["api"]
    networks:
      - app-network

  # 既存のtypescriptサービス
  typescript:
    build:
      context: .
      dockerfile: Dockerfile.typescript
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}-typescript
    depends_on:
      - claude
    environment:
      CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}-typescript
    profiles: ["typescript"]
    volumes:
      - .:/workspace
      - ${HOME}/.config/gh:/home/${USERNAME}/.config/gh:ro
      - ${HOME}/.gitconfig:/home/${USERNAME}/.gitconfig:ro
      - ${HOME}/.ssh:/home/${USERNAME}/.ssh:ro
      - ${HOME}/.zsh_history:/home/${USERNAME}/.zsh_history
      - ./apt-packages.txt:/home/${USERNAME}/apt-packages.txt
      - ${HOME}/.claude:/home/${USERNAME}/.claude
      - ${HOME}/.claude.json:/home/${USERNAME}/.claude.json
    tty: true
    working_dir: /workspace
    networks:
      - app-network
